/**
 * A/B test: navigation efficiency for Astra.
 *
 * Tests different system prompt strategies on the same question
 * and compares: answer quality, tool call count, cost, time.
 *
 * Usage:
 *   npx tsx tests/ab-navigation.ts
 *   npx tsx tests/ab-navigation.ts --variant A
 *   npx tsx tests/ab-navigation.ts --question "свой вопрос"
 */

import { spawn } from 'node:child_process'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__dirname, '..')

// ── Config ──

const TEST_QUESTIONS: Record<string, string> = {
  mwcf: 'насчёт сломанных ивентов на MWCF, мне бы пригодилось больше инфы. Я создаю тикет и мне нужно там прям подробно рассказать о проблеме. Помоги найти инфу и составить описание тикета на английском + название. Если есть ссылки на слак где обсуждалось - добавь их в описание',
  ac_updates: 'сегодняшние апдейты по Астро Коту',
}

const DEFAULT_QUESTION = TEST_QUESTIONS.mwcf
const TIMEOUT_MS = 300_000

// MCP config path (generated by bot, reuse it)
const MCP_CONFIG_PATH = resolve(PROJECT_ROOT, 'src/mcp/mcp-config.json')

const RESULTS_DIR = resolve(__dirname, 'ab-results')

// ── Base system prompt (shared by all variants) ──

const BASE_PROMPT = `You are Astra, a personal project management assistant. You help a senior PM manage daily routines: tasks, deadlines, meetings, emails, and team coordination. You are concise, proactive, and action-oriented.

Language: The user is writing in Russian. Always respond in the same language (ru).
Tone: Friendly but professional. Brief answers — no walls of text.
Honesty: If you don't know something, say so. Never make things up.

## User context
The user is Dariy (Дарий), a Senior PM.
His authorized Google accounts:
- dariy@astrocat.co
- dshatskikh@highground.games

Current channel ID: test-channel

## Integration tools
You have access to external service tools via MCP (Slack, Gmail, Calendar, ClickUp). All tools are read-only.`

// ── Knowledge map (from builder, hardcoded for test consistency) ──

const KNOWLEDGE_MAP = `## Organizational Knowledge
You have a structured registry of ALL projects, people, documents, and resources.

Projects (23):
AC: Star Trek Timelines, Oregon Trail, SpongeBob KCO, SpongeBob Get Cookin', Motor World: Car Factory, Idle Axe Thrower, Tough Guy, Aquarium, Vector, Symphonia, Puppet Master, Clash of Gods, Pong Breaker Royale, Block Puzzle [inactive], MOBA BACALHAU [inactive]
HG: Level One, Level Two, Pivot Pumps, Botox, HTML5 Banners, Playable Ads, Relevate Health Promo, Karl Storz [finished]

Resources indexed:
- 49 people (internal) + 16 external orgs
- ~195 Slack channels (classified by project)
- 17 ClickUp lists (3,987 tasks)
- ~70 Google Drive documents (with URLs, per-project catalogs)
- 1,442 Notion pages (5,081 chunks)
- 5 process descriptions

Registry data freshness: last updated 2026-03-15

Navigation: call kb_registry(project="X") to get full project card (team, channels, docs with URLs, tasks, status).
Call kb_registry(section="processes"|"wiki"|"drive"|"people"|"channels") for cross-project info.`

// ── Variant definitions ──

interface Variant {
  name: string
  label: string
  buildSystemPrompt: () => string
}

const variants: Variant[] = [
  {
    name: 'A',
    label: 'Baseline (current production)',
    buildSystemPrompt: () => {
      return `${BASE_PROMPT}

${KNOWLEDGE_MAP}

When answering questions about the organization, projects, people, or resources:
1. Use the knowledge map above to identify relevant sources
2. Call kb_registry(project=X) for full project details (team, docs, channels)
3. Then use specific tools: briefing() for live data, kb_search() for historical, audit_tasks() for compliance

## Data tools — live sources + Knowledge Base + Registry

**CRITICAL:**
- ALWAYS call actual tools. NEVER answer from conversation history.
- Never fabricate data — if results are empty, say so.
- If a tool fails, retry once. If still failing, tell user which service is unavailable.

### Navigation pattern (recommended workflow):
1. Check **Knowledge Map** in system prompt → identify project and relevant sources
2. **kb_registry(project=X)** → get full project card: team, Slack channels, Drive doc URLs, ClickUp lists, current status
3. Use specific names from the card to make targeted calls:
   - briefing(slack_channels=[...], clickup_list_names=[...]) for live data
   - kb_search(project="...") for historical/wiki data
   - audit_tasks(list_name="...") for compliance checks
4. Drill down: get_slack_thread(), get_email_content() for details

### Registry tool (start here for project/org questions)

**\`kb_registry(project?, section?)\`** — navigate the organizational Knowledge Registry.
- kb_registry(project="Aquarium") → full project card with team, channels, docs (URLs!), tasks, status
- kb_registry(section="people") → all internal + external people
- kb_registry(section="processes") → all processes across projects
- kb_registry(section="drive") → Google Drive document catalog index
- kb_registry(section="channels") → Slack channel directory
- kb_registry() → full knowledge map (table of contents)

### Decision strategy:

1. **Project info, team, docs** → kb_registry(project=X) FIRST
2. **Deadlines, milestones, historical facts** → kb_search
3. **Wiki rules, processes** → kb_search + kb_registry(section="processes")
4. **Current task status, today's updates** → briefing (live data)
5. **Verify tasks against rules** → audit_tasks
6. **People info** → kb_registry(section="people") + kb_entities
7. **Documents with URLs** → kb_registry(project=X) has Drive doc URLs

**Bail early — MANDATORY:**
If after 3 tool calls you haven't found what the user asked about, STOP and respond with what you know. For investigation/ticket-writing questions, allow up to 5 tool calls.`
    },
  },
  {
    name: 'B',
    label: 'Few-shot examples',
    buildSystemPrompt: () => {
      return `${BASE_PROMPT}

${KNOWLEDGE_MAP}

When answering questions about the organization, projects, people, or resources:
1. Use the knowledge map above to identify relevant sources
2. Call kb_registry(project=X) for full project details (team, docs, channels)
3. Then use specific tools: briefing() for live data, kb_search() for historical

## Data tools

### Registry tool — START HERE for org/project questions
**\`kb_registry(project?, section?)\`**
- kb_registry(project="Aquarium") → full project card
- kb_registry(section="people"|"processes"|"drive"|"channels")

### Live tools
- **briefing(sources, query_type, period, slack_channels?, clickup_list_names?)** — live data
- **kb_search(query, project?, period?)** — historical indexed data
- **audit_tasks(list_name)** — ClickUp task compliance check

### EXAMPLES — follow these patterns:

**Q: "Какие проекты на HG?"**
→ Answer from Knowledge Map above. NO tool calls needed.

**Q: "Что по Аквариуму?"**
→ 1 call: kb_registry(project="Aquarium") → full card with team, channels, status, docs.

**Q: "Найди обсуждение проблемы X на проекте Y, мне нужна инфа для тикета"**
→ 1 call: kb_registry(project="Y") → get Slack channels from card
→ 2 call: kb_search(query="проблема X", project="Y") → find historical context
→ 3 call: briefing(sources=["slack"], slack_channels=[channels from step 1], query_type="search", query="X") → find recent threads
→ Compile findings into ticket. Include Slack thread links if found.

**Q: "сегодняшние апдейты по Астро Коту"**
→ 1 call: briefing(sources=["slack","clickup"], period="today") → today's activity across AC projects
→ If need more specific data: briefing(sources=["gmail","calendar"], period="today")

**Q: "Кто работает на Level One?"**
→ 1 call: kb_registry(project="Level One") → team list in the card.

**Q: "Что обсуждали в Slack по Oregon Trail?"**
→ 1 call: kb_registry(project="Oregon Trail") → get channel names
→ 2 call: briefing(sources=["slack"], slack_channels=["oregon_tp","oregon_dev"])

### Rules:
- Answer from Knowledge Map when possible (project lists, company structure) — 0 tool calls
- For research/investigation questions: use kb_registry FIRST to get channels/lists, then targeted search
- Maximum 5 tool calls for complex investigation questions, 3 for simple questions
- NEVER call kb_registry() without arguments just to "check" — you already have the map above
- Bail early: if 2 calls found nothing useful, STOP and say what you checked`
    },
  },
  {
    name: 'C',
    label: 'Pre-resolved context (HG projects inline)',
    buildSystemPrompt: () => {
      return `${BASE_PROMPT}

${KNOWLEDGE_MAP}

## HG Project Details (pre-loaded for this conversation)

**Level One** — active | Slack: level-one-team, level-one-qa | ClickUp: "Level One - Tasks (~12)"
**Level Two** — active | Slack: level-two-team
**Pivot Pumps** — active | Slack: pivot-pump-team, hgg-pivot-custom | ClickUp: "Pivot - Tasks (~978)"
**Botox** — active | Slack: botox-team
**HTML5 Banners** — active | Slack: hgg-npp-drivers
**Playable Ads** — active | Slack: hg-playable-ads
**Relevate Health Promo** — active | Slack: relevate-health-promo, hgg-npp-drivers, relevate_health-high_ground
**Karl Storz** — finished

When answering questions about the organization, projects, people, or resources:
1. Use the knowledge map and pre-loaded context above FIRST
2. Only call tools if you need live/realtime data or details not in the context above
3. Call kb_registry(project=X) for full project details not shown above

## Data tools
- **kb_registry(project?, section?)** — full project card, registry sections
- **briefing(sources, query_type, period)** — live data from Slack/Gmail/Calendar/ClickUp
- **kb_search(query, project?, period?)** — historical indexed data
- **audit_tasks(list_name)** — ClickUp task compliance check

**Bail early:** max 3 tool calls. Stop and report what you found.`
    },
  },
  {
    name: 'D',
    label: 'Strict routing rules (no examples)',
    buildSystemPrompt: () => {
      return `${BASE_PROMPT}

${KNOWLEDGE_MAP}

When answering questions about the organization, projects, people, or resources:
1. Use the knowledge map above to identify relevant sources
2. Call kb_registry(project=X) for full project details

## Data tools
- **kb_registry(project?, section?)** — org registry (projects, people, docs, channels)
- **briefing(sources, query_type, period)** — live data (Slack, Gmail, Calendar, ClickUp)
- **kb_search(query, project?, period?)** — historical indexed data
- **audit_tasks(list_name)** — ClickUp task compliance check

## ROUTING RULES (follow strictly):

| Question type | Action | Max calls |
|---|---|---|
| Project list by company | Answer from Knowledge Map above | 0 |
| Project status/details | kb_registry(project=X) | 1 |
| Team composition | kb_registry(project=X) | 1 |
| Today's updates / daily digest | briefing(sources=["slack","clickup"], period="today") | 1-2 |
| Live Slack/email updates | briefing(sources=[...]) | 1-2 |
| Investigation for ticket/report | kb_registry → kb_search → briefing(slack search) | 3-5 |
| Historical facts | kb_search(query=...) | 1 |
| Task deadlines/overdue | briefing(sources=["clickup"]) | 1 |
| Document URLs | kb_registry(project=X) | 1 |
| Cross-project comparison | kb_registry per project | 2-3 |
| Process/rules lookup | kb_registry(section="processes") | 1 |

**CRITICAL:**
- The Knowledge Map above ALREADY lists all projects by company — do NOT call tools to list projects
- Simple questions: max 3 tool calls. Investigation/research: max 5 calls.
- If Knowledge Map answers the question → respond immediately, 0 tool calls
- NEVER call kb_registry() without arguments — you have the map
- For investigation: ALWAYS start with kb_registry(project=X) to get channel names, then targeted search
- Bail early: after 2 failed calls, stop`
    },
  },
  {
    name: 'E',
    label: 'Combined: few-shot + routing table + pre-resolved',
    buildSystemPrompt: () => {
      return `${BASE_PROMPT}

${KNOWLEDGE_MAP}

## Quick-Access Context

**HG Projects:** Level One (active, ClickUp ~12 tasks), Level Two (active), Pivot Pumps (active, ClickUp ~978 tasks), Botox (active), HTML5 Banners (active), Playable Ads (active), Relevate Health Promo (active), Karl Storz (finished)

**AC Projects:** Star Trek Timelines, Oregon Trail (ClickUp ~39), SpongeBob KCO, SpongeBob Get Cookin', MWCF (ClickUp), Idle Axe (ClickUp ~1029), Tough Guy, Aquarium, Vector, Symphonia, Puppet Master, Clash of Gods, Pong Breaker, Block Puzzle [inactive], MOBA [inactive]

## Data tools
- **kb_registry(project?, section?)** — org registry
- **briefing(sources, query_type, period)** — live data
- **kb_search(query, project?, period?)** — historical data

## ROUTING (follow strictly):

| Question type | Action | Calls |
|---|---|---|
| Project list | Answer from context above | 0 |
| Project details | kb_registry(project=X) | 1 |
| Today's updates | briefing(period="today") | 1-2 |
| Investigation/research | kb_registry → kb_search → briefing | 3-5 |
| Historical | kb_search() | 1 |

**Examples:**
- "Какие проекты на HG?" → Answer from Quick-Access above. 0 calls.
- "Что по Аквариуму?" → kb_registry(project="Aquarium"). 1 call.
- "Найди инфу о проблеме X для тикета" → kb_registry(project) → kb_search(query) → briefing(slack search). 3 calls.
- "Апдейты по Астро Коту" → briefing(sources=["slack","clickup"], period="today"). 1-2 calls.

**Rules:**
- Knowledge Map + Quick-Access answer project lists → 0 tool calls
- Simple questions: max 3 calls. Investigation: max 5 calls.
- After 2 failed calls → stop and report.
- NEVER call kb_registry() without arguments.`
    },
  },
]

// ── Claude CLI runner ──

interface RunResult {
  text: string
  toolCalls: number
  inputTokens: number
  outputTokens: number
  costUsd: number
  durationMs: number
  error?: string
}

async function runClaude(systemPrompt: string, userPrompt: string): Promise<RunResult> {
  const start = Date.now()

  const args = [
    '--print',
    '--no-session-persistence',
    '--model', 'sonnet',
    '--output-format', 'json',
    '--system-prompt', systemPrompt,
    '--max-turns', '30',
  ]

  // Add MCP config if available
  if (existsSync(MCP_CONFIG_PATH)) {
    args.push('--mcp-config', MCP_CONFIG_PATH)
    args.push('--permission-mode', 'bypassPermissions')
  }

  return new Promise((resolve) => {
    const proc = spawn('claude', args, { stdio: ['pipe', 'pipe', 'pipe'] })
    proc.stdin.write(userPrompt)
    proc.stdin.end()

    let stdout = ''
    let stderr = ''
    proc.stdout.on('data', (d: Buffer) => { stdout += d.toString() })
    proc.stderr.on('data', (d: Buffer) => { stderr += d.toString() })

    const timer = setTimeout(() => {
      proc.kill()
      resolve({
        text: '', toolCalls: 0, inputTokens: 0, outputTokens: 0,
        costUsd: 0, durationMs: Date.now() - start, error: 'TIMEOUT',
      })
    }, TIMEOUT_MS)

    proc.on('close', (code) => {
      clearTimeout(timer)
      const durationMs = Date.now() - start

      if (code !== 0) {
        resolve({
          text: stderr.slice(0, 500), toolCalls: 0, inputTokens: 0, outputTokens: 0,
          costUsd: 0, durationMs, error: `exit code ${code}`,
        })
        return
      }

      try {
        const parsed = JSON.parse(stdout) as {
          result?: string
          usage?: { input_tokens?: number; output_tokens?: number }
          total_cost_usd?: number
          num_turns?: number
        }

        // Count tool calls: num_turns from JSON (each tool call = 2 turns: request + result)
        // Subtract 1 for the initial user message turn
        const numTurns = parsed.num_turns ?? 0
        const toolCalls = numTurns > 1 ? Math.floor((numTurns - 1) / 2) : 0

        resolve({
          text: parsed.result ?? stdout.trim(),
          toolCalls,
          inputTokens: parsed.usage?.input_tokens ?? 0,
          outputTokens: parsed.usage?.output_tokens ?? 0,
          costUsd: parsed.total_cost_usd ?? 0,
          durationMs,
        })
      } catch {
        resolve({
          text: stdout.trim(),
          toolCalls: 0, inputTokens: 0, outputTokens: 0,
          costUsd: 0, durationMs,
        })
      }
    })

    proc.on('error', (err) => {
      clearTimeout(timer)
      resolve({
        text: '', toolCalls: 0, inputTokens: 0, outputTokens: 0,
        costUsd: 0, durationMs: Date.now() - start, error: err.message,
      })
    })
  })
}

// ── Main ──

async function runTest(question: string, questionLabel: string, toRun: Variant[]): Promise<Array<{ variant: Variant; result: RunResult }>> {
  console.log(`\n${'='.repeat(70)}`)
  console.log(`A/B Navigation Test — ${questionLabel}`)
  console.log(`Question: "${question.slice(0, 120)}${question.length > 120 ? '...' : ''}"`)
  console.log(`Variants: ${toRun.map(v => `${v.name}`).join(', ')}`)
  console.log(`MCP config: ${existsSync(MCP_CONFIG_PATH) ? 'found' : 'NOT FOUND (running without tools)'}`)
  console.log(`${'='.repeat(70)}\n`)

  const results: Array<{ variant: Variant; result: RunResult }> = []

  for (const variant of toRun) {
    console.log(`\n--- Variant ${variant.name}: ${variant.label} ---`)
    console.log(`Running...`)

    const systemPrompt = variant.buildSystemPrompt()
    const result = await runClaude(systemPrompt, question)

    results.push({ variant, result })

    console.log(`  Duration: ${(result.durationMs / 1000).toFixed(1)}s`)
    console.log(`  Tool calls: ${result.toolCalls}`)
    console.log(`  Tokens: ${result.inputTokens} in / ${result.outputTokens} out`)
    console.log(`  Cost: $${result.costUsd.toFixed(4)}`)
    if (result.error) console.log(`  ERROR: ${result.error}`)
    console.log(`  Response (first 500 chars):`)
    console.log(`  ${result.text.slice(0, 500).replace(/\n/g, '\n  ')}`)
    console.log()
  }

  // Summary table
  console.log(`\n${'='.repeat(70)}`)
  console.log(`SUMMARY — ${questionLabel}`)
  console.log(`${'='.repeat(70)}`)
  console.log(`${'Var'.padEnd(4)} | ${'Label'.padEnd(40)} | ${'Calls'.padEnd(6)} | ${'Time'.padEnd(8)} | ${'Cost'.padEnd(8)} | ${'Tokens (in/out)'.padEnd(16)} | ${'Resp len'.padEnd(8)}`)
  console.log(`${'-'.repeat(4)} | ${'-'.repeat(40)} | ${'-'.repeat(6)} | ${'-'.repeat(8)} | ${'-'.repeat(8)} | ${'-'.repeat(16)} | ${'-'.repeat(8)}`)

  for (const { variant, result } of results) {
    const time = `${(result.durationMs / 1000).toFixed(1)}s`
    const cost = `$${result.costUsd.toFixed(4)}`
    const tokens = `${result.inputTokens}/${result.outputTokens}`
    const respLen = `${result.text.length}`
    console.log(`${variant.name.padEnd(4)} | ${variant.label.slice(0, 40).padEnd(40)} | ${String(result.toolCalls).padEnd(6)} | ${time.padEnd(8)} | ${cost.padEnd(8)} | ${tokens.padEnd(16)} | ${respLen.padEnd(8)}`)
  }

  return results
}

async function main(): Promise<void> {
  const args = process.argv.slice(2)

  // Parse flags
  let selectedVariant: string | null = null
  let questionKey: string | null = null
  let customQuestion: string | null = null
  let allQuestions = false

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--variant' && args[i + 1]) {
      selectedVariant = args[i + 1].toUpperCase()
      i++
    } else if (args[i] === '--question' && args[i + 1]) {
      // Check if it's a shortcut key or a custom question
      if (TEST_QUESTIONS[args[i + 1]]) {
        questionKey = args[i + 1]
      } else {
        customQuestion = args[i + 1]
      }
      i++
    } else if (args[i] === '--all-questions') {
      allQuestions = true
    }
  }

  const toRun = selectedVariant
    ? variants.filter((v) => v.name === selectedVariant)
    : variants

  if (toRun.length === 0) {
    console.error(`Unknown variant: ${selectedVariant}. Available: ${variants.map(v => v.name).join(', ')}`)
    process.exit(1)
  }

  if (!existsSync(RESULTS_DIR)) mkdirSync(RESULTS_DIR, { recursive: true })

  // Determine which questions to test
  const questions: Array<{ key: string; text: string }> = []

  if (allQuestions) {
    for (const [key, text] of Object.entries(TEST_QUESTIONS)) {
      questions.push({ key, text })
    }
  } else if (questionKey) {
    questions.push({ key: questionKey, text: TEST_QUESTIONS[questionKey] })
  } else if (customQuestion) {
    questions.push({ key: 'custom', text: customQuestion })
  } else {
    // Default: run all test questions
    for (const [key, text] of Object.entries(TEST_QUESTIONS)) {
      questions.push({ key, text })
    }
  }

  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19)
  const allResults: Array<{ questionKey: string; question: string; variant: Variant; result: RunResult }> = []

  for (const q of questions) {
    const results = await runTest(q.text, q.key, toRun)

    for (const r of results) {
      allResults.push({ questionKey: q.key, question: q.text, ...r })
    }

    // Save individual responses
    for (const { variant, result } of results) {
      const responseFile = resolve(RESULTS_DIR, `${timestamp}-${q.key}-${variant.name}-response.txt`)
      writeFileSync(responseFile, [
        `# Variant ${variant.name}: ${variant.label}`,
        `# Question [${q.key}]: ${q.text}`,
        `# Tool calls: ${result.toolCalls}, Cost: $${result.costUsd.toFixed(4)}, Time: ${(result.durationMs / 1000).toFixed(1)}s`,
        `# Tokens: ${result.inputTokens} in / ${result.outputTokens} out`,
        ``,
        result.text,
      ].join('\n'), 'utf-8')
    }
  }

  // Save full results JSON
  const outputFile = resolve(RESULTS_DIR, `${timestamp}-results.json`)
  const fullResults = allResults.map(({ questionKey, question, variant, result }) => ({
    questionKey,
    question,
    variant: variant.name,
    label: variant.label,
    ...result,
    systemPromptLength: variant.buildSystemPrompt().length,
  }))
  writeFileSync(outputFile, JSON.stringify(fullResults, null, 2), 'utf-8')

  // ── Cross-question comparison (if multiple questions) ──
  if (questions.length > 1) {
    console.log(`\n${'='.repeat(80)}`)
    console.log('CROSS-QUESTION COMPARISON')
    console.log(`${'='.repeat(80)}`)

    for (const v of toRun) {
      const vResults = allResults.filter(r => r.variant.name === v.name)
      const totalCalls = vResults.reduce((s, r) => s + r.result.toolCalls, 0)
      const totalCost = vResults.reduce((s, r) => s + r.result.costUsd, 0)
      const totalTime = vResults.reduce((s, r) => s + r.result.durationMs, 0)
      console.log(`  ${v.name} (${v.label}): ${totalCalls} total calls, $${totalCost.toFixed(4)} total cost, ${(totalTime / 1000).toFixed(1)}s total time`)
    }
  }

  console.log(`\nAll results saved to: ${outputFile}`)
  console.log(`Individual responses: ${RESULTS_DIR}/${timestamp}-*-response.txt`)
}

main().catch(console.error)
